### ISSUE TITLE
How do we display the tasks in the duke.txt file when we first start up our GUI?

### ISSUE THREAD

**Issue by paing-oo** [nus-cs2103-AY2122S2/forum#111]
Since I have implemented GUI and stopped using text based UI, how do we display the tasks that was saved in the duke.txt file when we first launch the duke application?

**Comment by michaelseyo** [comment]
Hello! One way you could do it is by reading the lines in duke.txt file using a FileReader/BufferedReader, and parsing the lines accordingly to get the respective arguments needed to create the respective tasks upon launching your duke application so that you actually have the tasks inside instead of just getting the display of the tasks. This allows the user to continue on using Duke as per his last use with his previous tasks stored.

**Comment by xSaints19x** [comment]
Hello! Another way you could try is to change your ```execute``` method to return a ```String``` and call the ```list``` command and display the tasks in the MainWindow using ```dialogContainer.getChildren().add(DialogBox.getDukeDialog(savedTasks, dukeImage));```
Hope this helps! 😊
