### ISSUE TITLE
Not sure why read file is not registering the event task and deadline task

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2103-AY2122S2/forum#118]
Hey everyone, I think I've got a bug somewhere but I can't seem to find it...

Problem: 
![image](https://user-images.githubusercontent.com/83687861/152692245-51ed8112-0d4d-49fc-a9fa-9cc8f1b5e8fe.png)

**Initially, after adding an event or a deadline task to Duke, and subsequently listing them, the functionalities work, but after I close the application or execute the bye command, and thereafter relaunch the app to list tasks, the event, and deadline tasks somehow get "automatically" deleted.**

However, after trying to debug myself, I realized that the error might be stemming from the readFile(TaskList tasklist). Somehow, the switch statements work but the event task is not being instantiated and not being added to the task list.

I suspect this is the same reason why the same issue is happening for deadline tasks as well. However, I am not exactly sure why this is happening too. This issue came up after I tried to convert all my task lists methods to return Strings so that I can pass them into the getResponse(String input) in the Duke.java file.

Have been debugging for quite a while but not sure why it's happening too... appreciate anyone's help!

link to Storage.java: [link](https://github.com/yuqitanyq/ip/tree/master/src/main/java/duke/functionality)

code snippet:
```java
    public void readFile(TaskList taskList) throws DukeException {
        File information = new File(this.filePath);
        if (information.exists()) {
            try {
                File file = new File(this.filePath);
                Scanner sc = new Scanner(file);
                while (sc.hasNextLine()) {
                    String text = sc.nextLine();
                    String[] data = text.split(" \\| ");
                    String initial = data[0];
                    Task history;
                    switch (initial) {
                    case "T":
                        history = new Todo(data[2]);
                        break;
                    case "D":
                        history = new Deadline(data[2], Parser.convertDate(data[3]));
                        break;
                    case "E":
                        history = new Event(data[2], Parser.convertDate(data[3]));
                        break;
                    default:
                        throw new DukeException("Cannot understand the command");
                    }
                    if (data[1].equals("mark")) {
                        history.markAsDone();
                    }
                    taskList.addGeneralTask(history);
                }
            } catch (FileNotFoundException e) {
                throw new DukeException("Cannot find file...");
            }
        }
    }
```
*I have not edited the javadoc comments yet so it might be a little confusing for some of the methods that were initially void but now returns a String*

**Comment by limzk126** [comment]
Hi @yuqitanyq i am a Senior from previous batches of CS2103T (Dropping by to see if i can help you guys with technical problems! I know its a little late right now and i should probably get some sleep :D)

I tried debugging your code and found out that you are passing only the date string into the `Parser.convertDate()` method.
![image](https://user-images.githubusercontent.com/88614036/152695124-160c6f5f-bac6-45e1-90cd-dced3a7e38e6.png)
However, your `DateTimeFormatter` has a pattern that also requires the time as shown below, which is missing in your input.
![image](https://user-images.githubusercontent.com/88614036/152695194-4ea7f830-6034-4a8c-8a51-eaa820bfda0d.png)
As a result an exception is raised and caught which prevented your app from loading both event and deadline tasks.

To remedy this, you first need to save your list in the correct manner. i.e., It should contain the date and time in the correct format instead of just the date.

Bugs like this can actually be easily detected using Intellij's powerful debugger, which you will learn in week 6 I believe.

Also, as an additional tip 💡, you should use the `LocalTime.parse()` method if you want to retrieve the time too as `LocalDate.parse()` only retrieves the date.

Hope it solves your problem!
