### ISSUE TITLE
Discussion - Disabling fast forward merge in Git

### ISSUE THREAD

**Issue by waffledood** [nus-cs2103-AY2122S2/forum#121]
Hello Prof, CS2103 Teaching Team & fellow classmates! 

I was revising through Week 3's materials & wanted to clarify on the fast forward merge in Git. 

It's stated that Git will try to do a fast forward merge if possible (detects the branch accepting the merge has not changed since the branch being merged was created). 

I've personally been using `git merge branchToBeMerged` but had to switch to `git merge --no-ff branchToBeMerged` to avoid fast forward merges. 

I wanted to find a way to disable the fast forward merge & came across this [post](https://www.30secondsofcode.org/git/s/disable-fast-forward) that suggested executing `git config --add merge.ff false`. Hence, I wanted to consult Prof Damith, as well as everyone else's opinion on doing this & if it's bad/good practice? 

My reason for doing so is because I feel writing `git merge --no-ff branchToBeMerged` everytime would be troublesome & sometimes when working in a repo with multiple branches & so many changes, the developer might overlook this & instead write `git merge branchToBeMerged` since it is the shorter & more succinct command afterall. 

Appreciate any insights! 

p.s. this post can be tagged as "for-Discussion"

**Comment by domlimm** [comment]
Hello @waffledood ! I think it all boils down to preference. We were told to not do a fast forward merge so that we are able to see the `merge` commit. I believe it's mainly for our learning. Frankly, it is the first time that I'm using `git merge [BRANCH]` with the `--no-ff` flag. I've always just used `git merge` as it is. I don't think it's actually bad practice.

I guess also, in terms of readability, it's 'neater' in that sense you get to see like "Oh hey! This branch merged with X".

If not, it'd just be a combining line (if that makes sense) when you `git merge`.

Try typing `gitk --all` into your terminal (in your local project folder) to see how the merge is like. I believe there's a difference with the non-fast forward and the fast forward method.

And lastly, if I remembered correctly, you'd get a straight line in the commit history if there are no conflicts when doing a fast forward merge.

This is based on my personal experience.

Would love to hear from others too! 😄

**Comment by damithc** [comment]
> We were told to not do a fast forward merge so that we are able to see the `merge` commit. I believe it's mainly for our learning.

That's correct. It's because beginners will find it easier to follow when the merge is more obviously visible in the version graph. It's not meant to imply fast-forward is bad. Different alternatives (e.g., merge commit vs fast forward, squash, rebase) have their own pros and cons. For example, our TEAMMATES project uses the squash option which results in each PR being cleanly mapped to a single commit and a linear simple version graph (shown below), at the expense of losing all intermediate commits.

![image](https://user-images.githubusercontent.com/1673303/152933819-d078cce0-954c-451b-9afd-e9310de4176e.png)

**Comment by waffledood** [comment]
Thanks for the inputs Prof @damithc & @domlimm!
