### ISSUE TITLE
JavaFX tutorial 4 exercises

### ISSUE THREAD

**Issue by cheehongw** [nus-cs2103-AY2122S2/forum#126]
Hi everyone, what is supposed to be done for the second exercise of JavaFX tutorial 4?

![image](https://user-images.githubusercontent.com/72195240/153005175-d0071dad-d9a0-4f60-87ff-cc612ee4b705.png)

**Comment by AllardQuek** [comment]
Hi @cheehongw! I'm a senior popping by to see if I can offer some help :) I believe they are expecting something similar to what was mentioned above (i.e. setting the root node).

<img width="987" alt="image" src="https://user-images.githubusercontent.com/40263305/153119946-e8067424-bc29-47e3-9aec-c588608f8b12.png">

Have not attempted this exercise myself, but if anyone has a better idea, please do chip in 🙏 

(For future posts, you could also include the link to the [tutorial page](https://se-education.org/guides/tutorials/javaFxPart4.html) so that others who are trying to help can easily access it to get a better understanding of the context.)

**Comment by ngjunkang** [comment]
Hello! I will just share my implementation, not sure if it's what they are looking for. I arrived at my implementation after looking at [this](https://stackoverflow.com/questions/23600926/how-to-understand-and-use-fxroot-in-javafx). Notice that we were rendering the `fxml` file for `MainWindow` in `Main` and not in `MainWindow`, while `fxml` file for `DialogBox` is in itself.

I think the exercise wants us to abstract `MainWindow` into a node, so that we can easily reuse `MainWindow`, i.e. start two windows at once. My solution is abstracting most of the code of `Main` into the constructor of `MainWindow`, by referring to `DialogBox` and my `Main` class is simply as follows.

```java
@Override
public void start(Stage stage) {
    Scene scene = new Scene(new MainWindow(this.baron));
    stage.setScene(scene);
    stage.show();
}
```

I think this matches the first picture given [here](https://se-education.org/guides/tutorials/javaFxPart1.html), i.e. `MainWindow` as a root node containing nodes of nodes (DialogBox, Button).

In addition, there is a Java file modelling a `fxml` file exactly now, i.e. `MainWindow.java` models `MainWindow.fxml`. Using this way, the GUI component and its functional component are linked together now and we can use the GUI as an object now. I think this is very similar to the concept of Object–relational mapping (ORM) in database, where we create objects to map to database tables.
