### ISSUE TITLE
What does some classes do in AB-Level3?

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#133]
There are some classes that I do not fully understand the purpose of them. 
For example, there is this class called Argument Multimap and Im not sure what it does. 

This is the link to it: 
https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/logic/parser/ArgumentMultimap.java

Similarly, there are classes for each of the fields of the User object and I'm not sure the reason for doing so, please enlighten me!

An example:
https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/model/person/Email.java

**Comment by damithc** [comment]
@hsiaojietng Good question. Let's wait a while to see if others have inputs. I suspect most have not started looking at the AB3 code yet.

**Comment by tlylt** [comment]
Hi @hsiaojietng, 

I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). Just sharing my experience when working with AB3 (hope that's ok prof 😅)

I think it's very common for us to want to understand every single line of code that we are working on. However, this may not be the most efficient way to do things simply because at times, there might be too many details to focus on. And we don't necessarily need to know the code inside out in order to **start** working on it. In the context of AB3, I think some of the classes (like you mentioned, Argument Multimap etc) can indeed feel complex when you first look at it (I had the same feeling and it's perfectly normal!) 

What I would suggest you do to get a better idea of the purpose of each component, is to run the code locally with a debugger on (Note that this might in fact be mentioned as part of the upcoming tP tasks to get you familiar with the codebase) and step through the execution of some operations to see what code is being executed. For example, you will see how Argument Multimap works when the code executes the parsing logic of your input (IIRC). Once you have started working on the code in your tP, you will gain the required understanding of these classes in no time... especially when you are forced to use/edit/interact with them.
So don't be stressed and have fun coding!
