### ISSUE TITLE
Run jar file via double clicking instead of using the CLI

### ISSUE THREAD

**Issue by Btaykb** [nus-cs2103-AY2122S2/forum#135]
Hi prof and classmates, as the title suggests, I am trying to be able to run my jar file by simply double clicking on it (like the addressbook app) instead of having to go to the CLI and inputting `java -jar` filepath. I tried looking online for solutions but they don't seem to be solving the issue. Any help would be appreciated, thanks !

**Comment by domlimm** [comment]
Hello @Btaykb ! Once I've generated the JAR file, I'll just go to the `build` folder of my project and double click on it. Maybe you could try that and let us know how it goes!

**Comment by Btaykb** [comment]
Hi @domlimm! Hmm double clicking doesnt seem to do anything. 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/77221233/153551390-b45bd7b2-a3f6-46b0-97ed-7cbc2af79224.png">
Still have to manually get the file path and use it in the CLI.

**Comment by putaojuice** [comment]
Not sure if this helps but both the website i saw seems to suggest that you have to set some launcher to open the .jar file with.

https://discussions.apple.com/thread/8058941
https://stackoverflow.com/questions/8511063/how-to-run-jar-file-by-double-click-on-windows-7-64-bit

**Comment by domlimm** [comment]
These are the steps which I just used to generate my JAR file:

1. Delete my `build` folder

2. Run `shadowJar`

![image](https://user-images.githubusercontent.com/46486515/153552230-d328c430-2d7e-44b4-802a-fdba5004056b.png)

This is the output of the process:

![image](https://user-images.githubusercontent.com/46486515/153552315-3e61ca98-4f78-43de-8e7f-2cc6bd6bf97f.png)

3. Head to my `../build/libs/*` folder, and double click on the generated `JAR` file

![image](https://user-images.githubusercontent.com/46486515/153552560-d3d3f20b-68a4-4c2b-9b1e-6917453c1b57.png)

Sorry I should've said you need to double click on the `JAR` file from your `File Explorer/Finder (Mac)` because I don't think IntelliJ is able to do that for you directly. Let me know how it goes!

**Comment by Btaykb** [comment]
@putaojuice the weird thing is I am able to double click to run the addressbook jar file but for some reason my Duke jar file does not seem to work so I'm quite confused as well

@domlimm 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/77221233/153571304-f04341af-1e72-4795-9ce0-4b8cd4e43509.png">

This is what I get after running `shadowJar`. Unfortunately I still can't run it by double clicking in my File Explorer. Gonna check if Im missing anything...

**Comment by Btaykb** [comment]
So apparently the issue was that I did not add in the checks for the creation of the data directory and duke.txt file in the new gui files created for Level-10 (Main and Launcher). Added the checks in and my jar file now is able to be started up via double clicking. Thanks all for the responses and help !
