### ISSUE TITLE
iP: Doing regression testing for GUI output vs CLI output

### ISSUE THREAD

**Issue by limweiliang** [nus-cs2103-AY2122S2/forum#137]
Hi all,

After implementing the GUI, I realized we can't do testing via the text-ui-testing framework anymore, and there doesn't seem to be an equivalent way of testing the entire product when a GUI is being used.

I was thinking of writing a way to launch the bot without the GUI so that I could use the same text testing code, but was wondering if anyone else had a better idea?

**Comment by damithc** [comment]
@limweiliang You are not required to (see below) but you are welcome to keep using that way of testing.

![image](https://user-images.githubusercontent.com/1673303/153722015-202e757d-0c2f-4eef-ad60-91218d6d21dc.png)

Automated testing the entire product via the GUI is possible using tools such as TestFX but it takes a lot of extra work to implement and maintain. In fact the main difference between AB3 and AB4 is that AB4 has automated GUI testing. In the past we used AB4 as the starting point of the tP but switched to AB3 after a while because students found that way of testing too hard to work with.
