### ISSUE TITLE
Intellij not recognizing imports from within the tp directory

### ISSUE THREAD

**Issue by YiHern-Lee** [nus-cs2103-AY2122S2/forum#151]
So I'm using Intellij IDEA Community Edition 2020.3 and I'm trying to familiarize myself with the tp codebase. However, there is a problem with Intellij being unable to resolve imports of classes from within the project directory.

![image](https://user-images.githubusercontent.com/77192850/153985294-c11daee9-c591-4524-bfb1-35bb301da0f3.png)

Has anyone faced the same issue or knows how to resolve this?

**Comment by damithc** [comment]
@YiHern-Lee Common remedies you can try:
* File -> Invalidate cache
* Confirm you are following the exact steps given in the documentation when setting up the project in Intellij
* Try with a fresh clone

**Comment by ong6** [comment]
@YiHern-Lee If what prof mentioned does not work it might be due to other issues, 

You can try removing the unwanted source roots with the steps detailed [here](https://stackoverflow.com/questions/26952078/intellij-cannot-resolve-symbol-on-import/32999210#32999210):

1. Project Structure (Ctrl+Alt+Shift+S).
2. Modules
3. Select your problem module.
4. Change tab on top of window "Sources".
5. Remove unwanted source roots. Keep one and add src and test source roots in this root.

**Comment by YiHern-Lee** [comment]
Thanks, Prof @damithc and @ong6! Invalidating the cache worked for me.
