### ISSUE TITLE
iP dashboard not reflecting tags & Asking for the right way to commit

### ISSUE THREAD

**Issue by jbkim1999** [nus-cs2103-AY2122S2/forum#17]
Dear all,

I have completed my iP week 2 tasks on time, but it seems that the dashboard is not reflecting my tags beyond Level-4.

(So A-TextUiTesting, Level-5, and Level-6 are not reflected even after the dashboard was refreshed after I committed the tags already)

Moreover, on the iP code dashboard, it shows that I have 0 lines of code written, which is not the case.

I was wondering whether this is my fault on using the git commands.

Here is how I committed after done with each increment.

`git add .`
`git commit -m "With some messages"`
`git tag -a "tagName"`
`git push origin tagName`

I can see all my commits if I click on master branch -> Tags -> and appropriate level tags.

**Comment by s7manth** [comment]
Did you push your code to the remote (ie github)? If not, then the code won't be reflected on your ip repository.

**Comment by jbkim1999** [comment]
Sorry, there was a typo in my post, the last command should have been `git push origin Tagname`, so in a sense, I believe I pushed the tags explicitly to my remote repository. But I can only see them if I click on master branch -> Tags -> and appropriate level tags.

**Comment by damithc** [comment]
@jbkim1999 See the warning GitHub gives for this commit https://github.com/jbkim1999/ip/commit/ab776944aa9be6290de25b084a76c7056671fe95 (which is the host for one of the 'missing' tags)

![image](https://user-images.githubusercontent.com/1673303/150497184-fdcb9b25-b8ce-4897-a508-150a247c8bcb.png)


Our scripts only consider commits that are in the `master` branch.

**Comment by jbkim1999** [comment]
@damithc 

Hi prof, thanks for your input. But I got a little confused now.

So if I do `git push origin tagName`, (this I followed our website), where does that commit go? 

Do I have to push two times? (one for tag and one for master)

**Comment by VimuthM** [comment]
> So if I do `git push origin tagName`, (this I followed our website), where does that commit go?

This command merely pushes a tag and not the commit itself to origin. That's why you get the, "This commit does not belong to any branch..." message from the github interface because you pushed a tag to a commit that does not exist on the remote.

> Do I have to push two times? (one for tag and one for master)

Yes, usually you would push tags after your commits are pushed already. Something like: `git push && git push --tags` 

But this [SO](https://stackoverflow.com/questions/3745135/push-git-commits-tags-simultaneously) post has some answers to how you could do it at the same time, if you're interested (though it might be overkill).

**Comment by jbkim1999** [comment]
Thank you so much for the answer! I'll be sure to check out the post as well.
