### ISSUE TITLE
Requesting for help to test JAR file on linux

### ISSUE THREAD

**Issue by Btaykb** [nus-cs2103-AY2122S2/forum#180]
Hi, I am failing a smoke test for my JAR file on linux devices, would appreciate any help in testing this new release. 
https://github.com/Btaykb/ip/releases/tag/v1.1
Thank you!

**Comment by yusufaine** [comment]
The only thing I can think of is the line [here](https://github.com/Btaykb/ip/blob/06939f15794d05032259b42a9bb0c8af2073f1ee/src/main/java/duke/Duke.java#L29).

I made my as a relative path using (localising it to your case) `data/Duke.txt`. I'm not sure if making this change would make any difference since it's functionally the same as `./data/Duke.txt`, but maybe you can give it a shot?

**Comment by damithc** [comment]
Also make sure you don't use `duke.txt` and `Duke.txt` interchangeably -- that will work in Windows but not in Linux.

**Comment by yusufaine** [comment]
Adding on to what prof said, in Duke you declared the filepath to be `./data/Duke.txt` but in FileHandler::readFromFile, it's reading from `./data/duke.txt`

I'm not sure if there are any other mismatched duke/Duke but a suggestion would be to store the path in a variable and passing it around where necessary
