### ISSUE TITLE
tP: What to do with branches on our personal repo?

### ISSUE THREAD

**Issue by NatalieTanML** [nus-cs2103-AY2122S2/forum#184]
As mentioned in the [tP workflow](https://nus-cs2103-ay2122s2.github.io/website/admin/appendixE-gitHub.html#tp-workflow), each member should have their own fork from the main repo, and create a separate branch for each PR. After the PR is merged into the main repo, is it necessary to delete the branches from our own fork or should we leave it as it is?

**Comment by damithc** [comment]
@NatalieTanML It's best to not delete branches in the tP (although it is common practice to do so in normal practice), as our grading scripts checks if you have used branches as required.

**Comment by yusufaine** [comment]
From my understanding, it isn't necessary to delete the branch after the PR has been merged in the team's repo and the choice of removing it might be personal ~~but I'm not sure if it would affect our grading~~ (Prof replied while I was writing this -- it does).

Personally speaking, I tend to leave feature branches open even after the PR has been merged in case I need to make slight modifications to it. Similar for updating documentation, I tend to leave it open so that I have one branch to make all those changes

**Comment by NatalieTanML** [comment]
Thanks for the input!
