### ISSUE TITLE
How to solve Java CI problem

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#197]
I am trying to push my branch into my team repo, everything seems fine (resolved all conflicts) but when I create the PR and the CI runs, I encounter this error:
![image](https://user-images.githubusercontent.com/56862300/156371994-9bf56492-ee83-423f-93d0-a167a88e725c.png)

I am pushing from my own repo's master branch into the team repo's master branch, don't know if that is an issue.

View the PR for more information here: https://github.com/AY2122S2-CS2103-W16-4/tp/pull/33.

**Comment by yusufaine** [comment]
@hsiaojietng according to error-labeled lines (4, 5, 6) of the screenshot, all you have to do is add an empty line at the end of `DeveloperGuide.md`, `User Guide.md`, and `howardwong.md`

This check was probably made in place because github doesnt play nicely with files that dont end with an empty line

**Comment by damithc** [comment]
@hsiaojietng Regarding the trailing whitespace problem, if using Intellij, refer to https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-auto-remove-trailing-spaces

**Comment by hsiaojietng** [comment]
Thanks @damithc. I actually already have that setting. Not sure why it is not working

**Comment by AAlghrairy** [comment]
Try right-clicking the files that contain these errors and select `Reformat Code`.
