### ISSUE TITLE
Why filteredlist.sort() method fails.

### ISSUE THREAD

**Issue by Jacky142857** [nus-cs2103-AY2122S2/forum#198]
This question may nothing to do with the project. So filteredlist implements list and has sort() method built in. However, when I try to apply sort() on filteredlist, it fails.  but for observablelist, it works fine.

**Comment by yusufaine** [comment]
Hi, could you provide a little more detail about filteredlist such as what's the type that you're storing in there?

**Comment by Jacky142857** [comment]
> Hi, could you provide a little more detail about filteredlist such as what's the type that you're storing in there?

![image](https://user-images.githubusercontent.com/77191979/156613937-ddc8946a-ec27-4886-b362-a8b7a4e80f97.png)
So the list.sort() works fine but flist.sort() crashes, since they both implement list, it is quite wired to see this situation

**Comment by yusufaine** [comment]
@Jacky142857 I'm not sure if this is the correct answer but from my testing, it seems like `FilteredList` is read-only ("truly-immutable", which is why it's initialised the way that it is). The only way to change it is by modifying the input ObservableList as mentioned in the [docs](https://docs.oracle.com/javase/8/javafx/api/javafx/collections/transformation/FilteredList.html#:~:text=Wraps%20an%20ObservableList%20and%20filters%20it%27s%20content%20using%20the%20provided%20Predicate.%20All%20changes%20in%20the%20ObservableList%20are%20propagated%20immediately%20to%20the%20FilteredList.):

> Wraps an ObservableList and filters its content using the provided Predicate. All changes in the ObservableList are propagated immediately to the FilteredList.

If you still want to sort the FilteredList without the underlying ObservableList, I think you can use the `ObservableList::sorted()`, and your highlighted line would be something like `flist.sorted()`.

Hope that helps!
