### ISSUE TITLE
HelpWindow Class in tP

### ISSUE THREAD

**Issue by tiewweijian** [nus-cs2103-AY2122S2/forum#204]
Hi, 

Was wondering if `HelpWindow` class could be instantiated by itself? I wrote a new method in this class and am required to test it, and I observe how `HelpWindow` is called from `MainWindow`. 

```
helpWindow = new HelpWindow();
```

```
    @FXML
    public void handleHelp() {
        if (!helpWindow.isShowing()) {
            helpWindow.show();
        } else {
            helpWindow.focus();
        }
    }
```

However in HelpCommandTest, when I call `HelpWindow` as the following, it will give an error. 

```
HelpWindow helpWindow = new HelpWindow(); 
``` 

What is the correct way to call `HelpWindow`, and what is the best method to test methods within the class?

**Comment by damithc** [comment]
@tiewweijian are you attempting to do automated GUI testing?

**Comment by tiewweijian** [comment]
I was trying to test a method in `HelpWindow` class, but I was not able to test it by calling 

I tried to write this codes in the test java files like this. 

```
HelpWindow helpWindow = new HelpWindow(); //this line gives an error 
assertTrue(helpWindow.goToUrl()); 
```
`goToUrl()` lets the user to access the User Guide by clicking on the button. 
Was suspecting that the codes were related to the GUI itself, and will be difficult to test mentioned in #201

**Comment by damithc** [comment]
@tiewweijian Let's wait a while to see if others in the class has anything to offer on this. In the meantime, you can put testing portion on hold if it is not urgent.
It is also advisable to offload as much of the GUI logic as possible to non-GUI classes so that such logic can be tested without activating any GUI classes. For example, you can have a regular class `HelpWindowUtils` containing some methods that the `HelpWindow` class uses. Testing the `HelpWindowUtils` class will be easier compared to testing the `HelpWindow` class.

**Comment by tiewweijian** [comment]
thanks prof ! will look more into creating another class to fulfill the intended purpose. Will update here accordingly if there are any new insights about testing through the `HelpWindow` class as well!
