### ISSUE TITLE
Problem with updating information in GUI

### ISSUE THREAD

**Issue by Punpun1643** [nus-cs2103-AY2122S2/forum#217]
I'm having a lot of problems trying to reflect information on the GUI correctly. My GUI currently has a `GroupCard` which represent a `Group`. A `Group` contains a `UniqueTaskList` which contains `Task` in that `Group`.  

I can successfully show all current tasks in the group card in the GUI. However, the problem comes when I want to execute commands that add or delete tasks from a group. The GUI could only automatically update the task list on the first command. For each subsequent command, I would have to manually click on the respective card in the GUI for it to reflect the current task list. 

I have checked that the task list is being updated properly in the json file after the add/delete task command execution.

Are there any suggestions on the issue I could look into? For now, I can't even point out where the possible issue might be and I have been trying to solve this for a few hours already.

My code could be accessed from this branch [here](https://github.com/Punpun1643/tp/tree/task-GUI)

This is a screenshot for the problematic part from my GUI 

![Screenshot 2022-03-18 at 9 07 46 PM](https://user-images.githubusercontent.com/60144099/159009638-3d247d83-3c16-4450-94ef-6c3b842c3f9d.png)

Any insights would really help a lot!

**Comment by damithc** [comment]
While waiting for inputs from others, perhaps you can do a careful comparison between the code for the person list and your group list? It seems the two lists are meant to work similarly and hence, as the person list is working already, the code for the group list will have to be very similar to the code of the first. In fact a good strategy is to copy-paste-modify the code from the person list to create the group list.

**Comment by vimuthm** [comment]
Hi @Punpun1643 

On a cursory glance, I think the issue lies in this method inside `AddressBook.java`

```
    /**
     * Adds a task to a specified group from the address book.
     * The group must already exist in the address book.
     * The task must not already exist in the specified group in the address book.
     */
    public void addTask(Task task, Group g) {
        groups.getGroup(g).addTask(task);
    }
```

For any gui updates, the `ObservableList<Group>`s methods such as `set`, `add`, `setAll` etc should be called. Above, you are simply getting the Group object and mutating it by adding a task. This change will not be "seen" by the `ObservableList` as the `UniqueGroupList` is not being changed.

You should probably try to do something similar to how a `Person` is modified, ie Create a copy of the Group, add a task to the copy, then `set` the "old" group object with the "new" group object.

A different way (I'm not too sure), is to embed your `UniqueTaskList` within each `Group`. Then on addition of a task, re-rendering of the task list alone will happen. (I can't vouch for this method, just an idea)

Let me know if an implementation as first mentioned doesn't work out!

ps. command format for `addtask` differs in the help window vs what is implemented :")

**Comment by Punpun1643** [comment]
Hi @VimuthM thanks so much! Will try to implement it later and update here! 

And yup, I have yet to update the command format in the help window. Thanks for pointing that out too!

**Comment by Punpun1643** [comment]
Hi, @VimuthM just an update that I tried implementing the first method and it works so didn't really try out the second method due to time constraints. The problem is indeed from the `addTask` method. Thanks so much! Will be closing this issue now 😄
