### ISSUE TITLE
Should we enable support for the same font on macOS systems(e.g Segoe UI or a new Font) or document it as a bug? 

### ISSUE THREAD

**Issue by zzhikai** [nus-cs2103-AY2122S2/forum#239]
I was looking for fixes or standardising how fonts appear on different systems as 'Segoe UI' and its relevant styles('Segoe UI Bold', 'Segoe UI Black' etc.) does not show on macOS. 
So I am wondering if we should enable support for a universal font across systems for our tp or document it as a bug.

I referenced the following and was left with the impression to leave things as is now. 
https://github.com/se-edu/addressbook-level3/pull/106
https://github.com/se-edu/addressbook-level3/pull/119

**Comment by damithc** [comment]
@zzhikai It is fine to leave things as it i.e., let the OS fallback on a suitable font if the specified font is not available. But you are welcome to package the fonts in the JAR so that the font remains the same across OS too. It's arguable if standardizing is better than letting the font 'adapt' to the OS.

**Comment by zzhikai** [comment]
@damithc Alright thank you!
