### ISSUE TITLE
Does manually editing JSON files count as bugs in PE?

### ISSUE THREAD

**Issue by lzan98** [nus-cs2103-AY2122S2/forum#243]
Hi Prof @damithc ! 

Sorry to disturb, but may I check if a user edits the JSON file manually on purpose, and it results in some unintended behaviour (for example, [this issue raised in a previous PE](https://github.com/nus-cs2103-AY2021S2/pe-dev-response/issues/3119#issue-859990313)), will we be penalized for it? 

In the linked issue, it is mentioned that it is not considered a bug, but I would like to clarify if the same still applies for this semester 😥 

Thank you!

**Comment by damithc** [comment]
Good question @lzan98 The last point in the screenshot below (taken from https://nus-cs2103-ay2122s2.github.io/website/admin/tp-pe.html) below states our policy on that.
![image](https://user-images.githubusercontent.com/1673303/160859216-c441927c-59b2-41ad-ac41-34db1447acbc.png)

In addition, as per https://github.com/nus-cs2103-AY2021S2/forum/issues/304#issuecomment-816803396
>The AB3 stance is (although not explicitly stated), "if you modify the data file, you'd better know what you are doing". Nothing is guaranteed if the user makes a mistake in the data file. While this stance is not ideal, it's still a fair stance and is good enough for the tP.
It's great if you handled such 'invalid data in the JSON file' situations. But I don't think we want to enforce it as a requirement or consider it as a bug, especially because we didn't mention such a requirement earlier.

**Comment by lzan98** [comment]
Thank you Prof @damithc for the clarification! Understood :)
