### ISSUE TITLE
Sort command questions

### ISSUE THREAD

**Issue by Jacky142857** [nus-cs2103-AY2122S2/forum#244]
There are several implementations that I am not sure about sort command:
1. when sorting a list with an optional field(e.g. date/time) for those entries without a date/time field, should they be displayed in the list?
2. When sorting according to alphabetical order, the order is like AB.....Zab...z, which the small letter 'a' is after capital letter 'Z' which is quite counter-intuitive, should I leave the order like this, or convert the field to capital letter when comparing, or auto-convert the something to capital letter whenever user entered something

**Comment by damithc** [comment]
@Jacky142857 The general answer for this is, "depends on the context". Choose whatever option that makes most sense to the user using that specific sorting feature. In addition, you may want to keep the user informed of whichever choice you make, through the UI and/or the UG.

**Comment by jbkim1999** [comment]
I think one way is to make date/time a mandatory field, but if not, I think the decision is up to your team. 
Likewise, for sorting, you may define your own Comparator and sort it as you wish.

But I think the most important thing is to document those changes so that the users know what to expect!

**Comment by putaojuice** [comment]
For the first point, it really depends on what you want to achieve imo. If you still want to allow the user to view all the things in the list, perhaps you could display it after those entires with a date/time

Secondly, I think in most applications, sorting is done based on alphabetical order in most cases, disregarding the upper or lower cases, it makes more sense to me as a user to see entires in alphabetical order and not affected by the letter being upper or lower case!

Hope this helps with you team's decision

**Comment by charmainehly** [comment]
I noted an interesting extension/implementation from a TP, which could be an additional point for consideration depending on the context. 

Given as there are multiple possible fields to sort by for the team's application, they actually enhanced the sort command to include: 1. allowing the user to decide whether to sort a field by ascending or descending, as well as 2. allowing users to sort by multiple fields in terms of priority (i.e. the lower priority fields will be used as a tie breaker when sorting if the higher priority field is a duplicate/identical).

Though we are in a feature freeze now, just thought it was an interesting point I took note of. Perhaps given the context that there are multiple possible needs of a user, it could mean that the functionality of the application itself should provide the user more autonomy to decide how the sorting should go - but again perhaps there needs to be a balance of ensuring the user doesn't have to decide too many constraints just for the sorting to work!

**Comment by xSaints19x** [comment]
I would like to add my take on this based on what I've seen thus far:

Regarding your 1st question, since typically what would be expected of the `sort` command is that it just sorts the data without removing any "unwanted" data. You could sort the data with the optional field in the list and place it before/after the data without the optional field depending on how your team would want it. If you wish not to display the data in the list without the optional field, it would be good to have a `filter` command instead which makes it more intuitive for the user.

As for your 2nd question, maybe a good way of avoiding that situation is to standardise how you would want to store the input from your user. For example, one simple example is to capitalise the 1st letter of a word or words and keep the rest lower case e.g `John` or `John doe`.

Hope this helps!
