### ISSUE TITLE
Naming for file submissions

### ISSUE THREAD

**Issue by bingsen0806** [nus-cs2103-AY2122S2/forum#268]
According to the email sent out, our file submissions are supposed to be named something like this:

`[CS2103T-W14-1][PRODUCT_NAME].jar`
`[CS2103T-W14-1][PRODUCT_NAME]UG.pdf`
etc.

My question is, if my software is `LibTask` (as shown in all documentation and code), but the jar file name is `libtask.jar`, should `PRODUCT_NAME` be ` LibTask or libtask?

My concern is that if I name it as `[CS2103T-W14-1][LibTask].jar`, the testers will download it as `LibTask.jar`. In my documentation, I stated that they can run the app using `java -jar libtask.jar` command. This will no longer work. What will the names of the jar file be, after the testers have downloaded it? Will they download from luminus directly?

**Comment by damithc** [comment]
@bingsen0806 In the documentation, you can mention something like ` (assuming you saved the file as libtask.jar)` because users can rename the JAR file and sometimes files get auto-renamed by the Browser/OS when you download them. 
The testers will be given a file named `[CS2103T-W14-1][LibTask].jar` but that should not be a problem if you do the above.
