### ISSUE TITLE
Flagging Low Quality Bug Reports

### ISSUE THREAD

**Issue by sharpstorm** [nus-cs2103-AY2122S2/forum#280]
Hi Prof,

I would like to ask for the Dev Response phase, is there any way that we can flag issues that the team thinks are low quality and excessively duplicated (the text is exactly the same except for 2 or 3 words without any screenshots)?

It seems ridiculous that this one person is single-handedly tanking our percentage of accepted bugs and the dev team has to eat the penalty (or rather not have the chance to go for the 60% threshold of accepted issues) for it.

**Comment by damithc** [comment]
@sharpstorm **we reward accuracy, not acceptance rate**. There is no penalty for rejecting bugs that deserve to be rejected. Even if your reject all your bugs and they remain rejected (and the other labels you chose remain too) at the end of the remaining two phases, your accuracy will be 100% and you will be rewarded for it. However, your accuracy will be affected if you reject a bug that is later disputed by the tester and the teaching team rules in favor of the tester. If your reason for rejection is accepted by either the tester or the teaching team, you should be fine.

Therefore, a tester cannot lower your marks by submitting low quality bug reports or duplicates. 
* If the bug report is rejected by you and the rejection stands at the end (the chances of that are higher because the bug report is of low quality), it will only improve your accuracy percentage (because your rejection was correct) and lower the accuracy of the tester. 
* Duplicates are counted as one bug (from the receiving team's point of view), so that shouldn't affect your marks or accuracy either.

**Comment by sharpstorm** [comment]
Alright, Thank You Prof! I seem to have misunderstood the bonus marks write-up of the Dev Response phase on the website, sorry about that and thank you for correcting me.
