### ISSUE TITLE
Missing in application but not in UG

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2103-AY2122S2/forum#281]
Hi prof,

In the code freeze, it is not possible to add / change error messages. However, the error message in V1.4 is not specific enough. 

For example: 
In the UG we have added a sentence where deleting 1 entry will cascade to other entries given some condition

However, it is not present in the message in the application. (although the functionality is correct)

Is it reasonable to assume that the users already read the UG before testing the app? If not, then what is the correct severity of this?

**Comment by damithc** [comment]
@albertsutz 
* Having it mentioned in the UG certainly justify a lower severity than otherwise.
* Another factor to consider is the natural expectation of the users: would they naturally expect the delete to cascade to the other items? If yes, a lower severity is justified i.e., the behavior is 'as expected' irrespective of whether it is described in the error message or the UG.
* 'Missing more specific details' is lower severity than 'incorrect info'.

But how low can you go, is a decision you have to make :-)

**Comment by albertsutz** [comment]
Thanks prof!
