### ISSUE TITLE
Java Coding Standard for Boolean Methods/Variables Confusing.

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2103-AY2122S2/forum#29]
According to the Java coding standard for this module, boolean variables/methods should be named to sound like booleans.
```
//variables
isSet, isVisible, isFinished, isFound, isOpen, hasData, wasOpen

//methods
boolean hasLicense();
boolean canEvaluate();
boolean shouldAbort = false;
```
But wouldn't this make the getters confusing with variables? Consider this:
```
public class Foo {
    private boolean isDone;

    public Foo() {
        isDone = false;
    }

    // The method has the same name as the variable.
    public boolean isDone() {
        return isDone;
    }

    // ...
}
```

While the above example is legal code, wouldn't this make it easy to mistake the variable and a function call of the getter?

**Comment by takufunkai** [comment]
Personally I don't see why this could be confusing. The client should not know and have anything to do with the `isDone` private boolean field, and the implementation shouldn't be using the `isDone()` public accessor method.

And although there could be some scenarios where an accessor method is necessary, I feel that it is usually possible to refactor the code such that accessor methods are unnecessary. For example, instead of checking if a ToDo task is done, we can focus on what we need to do with that information, and request the ToDo class handle that instead. This way we don't have to do `isDone()` accessor.
