### ISSUE TITLE
AB3 showing random text

### ISSUE THREAD

**Issue by garethkoh** [nus-cs2103-AY2122S2/forum#35]
Hi does anyone know why AB3 looks like this whenever i open it? When i type into the section that is supposed to say "enter command here", my text also appears incorrectly.

 I am using MacOS Monterey and have Java 16 installed on my computer
<img width="742" alt="Screenshot 2022-01-26 at 2 24 09 PM" src="https://user-images.githubusercontent.com/77238736/151113829-e0a16276-e8f5-4a50-a509-0e56bfc50145.png">

**Comment by cheehongw** [comment]
seems like an expected issue from AB3's issues page

see: https://github.com/se-edu/addressbook-level3/issues/120

**Comment by damithc** [comment]
@garethkoh see the advisory for Mac users given in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language

Post here if that doesn't fix the problem for you

**Comment by SimJM** [comment]
@garethkoh I encountered the same problem and managed to resolved it by downloading the v0.2.0.ea instead of the latest version v0.2.1.ea. https://github.com/se-edu/addressbook-level3/releases

**Comment by damithc** [comment]
> @garethkoh I encountered the same problem and managed to resolved it by downloading the v0.2.0.ea instead of the latest version v0.2.1.ea. https://github.com/se-edu/addressbook-level3/releases

@SimJM That specific version has a fix for this font problem which we have reverted since. Hence, it will only give you a false sense of security -- the problem will resurface when you work with your own tP JAR files later. The long term solution is to install the JDK version mentioned in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language

**Comment by SimJM** [comment]
@damithc Noted. Thank you for the clarification. :)

**Comment by garethkoh** [comment]
@damithc Thank you prof, it works now!
