### ISSUE TITLE
Issue pushing a commit on SourceTree

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2103-AY2122S2/forum#4]
Hey everyone,
I am trying to push my commit to origin on SourceTree, but somehow SourceTree keeps giving me this error:

`git -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags origin refs/heads/master:refs/heads/master 
Pushing to https://github.com/yuqitanyq/ip.git
remote: Permission to yuqitanyq/ip.git denied to yuqitanyq.
fatal: unable to access 'https://github.com/yuqitanyq/ip.git/': The requested URL returned error: 403
Completed with errors, see above`

I am a mac user and for some reason, SourceTree keeps asking for keychain access on my mac when I push my commit, but after giving access this error just pops up.

I've tried googling and managed to find a thread on this issue on Atlassian:
[https://community.atlassian.com/t5/Sourcetree-questions/Unable-to-push-a-commit-to-Github-repository/qaq-p/1034485](url)

but am still not really sure how to make it work. Has anyone who is a mac user been able to use HTTPS as your protocol and still manage to push your commit without seeing this error?

Thank you.

**Comment by Spyobird** [comment]
Hello,

the issue you are facing may be due to [token authentication](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) for HTTPS. Perhaps you could try one of these solutions.

Setting your authentication credential to the git remote URL:
`git remote set-url origin https://yourusername@github.com/user/repo.git`

Creating a personal access token:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Alternatively you can try and use SSH, which might be less hassle in the future.

I am not a mac user but hope this may help resolve the issue.

**Comment by HolmesJJ** [comment]
I think this https://github.com/nus-cs2103-AY2122S1/forum/issues/25 will work.

I think you can set your password as your token when your generated based on @Spyobird.

And this is a video for your reference
https://dev.to/arjuncodes/support-for-password-authentication-was-removed-on-august-13-2021-fixed-k1e

**Comment by jaysmyname** [comment]
I had the same problem, and imo the best and easiest fix is from this thread:
https://github.com/nus-cs2103-AY2122S1/forum/issues/13

which has this answer:
https://stackoverflow.com/a/68784631

**Comment by yuqitanyq** [comment]
> Hello,
> 
> the issue you are facing may be due to [token authentication](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) for HTTPS. Perhaps you could try one of these solutions.
> 
> Setting your authentication credential to the git remote URL: `git remote set-url origin https://yourusername@github.com/user/repo.git`
> 
> Creating a personal access token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
> 
> Alternatively you can try and use SSH, which might be less hassle in the future.
> 
> I am not a mac user but hope this may help resolve the issue.

@Spyobird for the first method, is it a long-term solution? Or is it a short-term solution like the personal access token? I tried the personal access token method and it worked haha. But since the token has an expiry date it's a short-term solution, right?

I wasn't really sure how to do the first method, does this mean that if I were to do the first method, I would have to type `git remote set-url origin https://**yuqitanyq**@github.com/user/**ip**.git` in my terminal? 

Are both solutions short-term solutions and ssh is the one that will work for every repo in the future if I use source tree?

**Comment by yuqitanyq** [comment]
Thanks though everyone @HolmesJJ @Spyobird @jaysmyname who contributed! The personal access token definitely works!

**Comment by Spyobird** [comment]
I believe that you can set the expiration for the personal access token. I think the default duration is 30 days, but you probably can set it longer, even to no expiration I believe (although that might have security implications). The point of personal access tokens is to be temporal. This allows it to be unique and random which preserves its authenticity, however you could probably set one that covers the duration of the module so you don't have to worry about it too much.

As for SSH, its benefit is so that you don't have to constantly re-enter your credentials whenever you want to use git commands, which can save with some hassle. Although that being said you could probably cache your personal access token for it to behave in a similar way (auto-filling passwords).

I believe SourceTree has OAuth support too, which may just simplify the entire issue of connecting with HTTPS/SSH. However, I am not sure if there would be any other issues when using OAuth. At the end of the day, it is just using the method which works for you.

**Comment by yuqitanyq** [comment]
Oh, @Spyobird mine was initially OAuth together with HTTPS in source tree preference settings, but i think the password login credential authentication did not work. 

Thanks though!
