### ISSUE TITLE
JavaFX GUI display weird text

### ISSUE THREAD

**Issue by zzkzzzz** [nus-cs2103-AY2122S2/forum#58]
Hi, when I tried JavaFx tutorial, it showed weird text. I am using macOS BigSur.

The error message is `2022-01-30 15:02:13.803 java[44318:4457012] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].`

I think this is related to my system default font and how can I change the font?
![image](https://user-images.githubusercontent.com/44489498/151690202-a4e55386-a1f7-4049-8255-d8cda1df1b63.png)

**Comment by yunbinmo** [comment]
I had the same issue, I guess you are creating a new project for the JavaFX tutorial with default settings, the problem probably lies with the SDK you are using, and by doing the following fix my problem:
In IntelliJ, go to the file tab -> Project Structure -> Project Settings, under the Project section, change the SDK to the one suggested [here](https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html), and restart IntelliJ.
Hope this could help!

**Comment by zzkzzzz** [comment]
> I had the same issue, I guess you are creating a new project for the JavaFX tutorial with default settings, the problem probably lies with the SDK you are using, and by doing the following fix my problem: In IntelliJ, go to the file tab -> Project Structure -> Project Settings, under the Project section, change the SDK to the one suggested [here](https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html), and restart IntelliJ. Hope this could help!

Thanks a lot! It solved the issue.

**Comment by michaelseyo** [comment]
Hello I've the same issue as well, i'm using MacOS catalina and i've used the java version as you've stated in the link?
![Screenshot 2022-01-31 at 7 17 13 PM](https://user-images.githubusercontent.com/76872115/151784601-99b820a1-9f66-4541-abb3-b7ab8d981d75.png)

**Comment by jamesyeap** [comment]
Not sure if this is recommended but changing the javaFxVersion to 14 in `build.gradle` worked for me:

![Screenshot 2022-01-31 at 8 05 21 PM](https://user-images.githubusercontent.com/34131671/151791265-6da7df29-3b06-4877-9161-be85031059fc.png)

**Comment by michaelseyo** [comment]
Thank you so much james it works great now!! :)

**Comment by damithc** [comment]
> Hello I've the same issue as well, i'm using MacOS catalina and i've used the java version as you've stated in the link?

@michaelseyo Confirmed you are using **Azul** build `JDK FX` version (note `FX`), as specified [here](https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language)?

**Comment by michaelseyo** [comment]
@damithc i'm using the one the oracle version as stated in the link, if i put the javaFxVersion = '11' it doesn't seem to work, having the same error message, but @jamesyeap suggestion of putting it to '14' works

![Screenshot 2022-01-31 at 9 20 17 PM](https://user-images.githubusercontent.com/76872115/151800682-9886deb8-4d6d-4bd1-9f73-f1a4f4a1c5c3.png)

![Screenshot 2022-01-31 at 9 19 31 PM](https://user-images.githubusercontent.com/76872115/151800546-1f06f921-43c4-4fff-b820-defd9c87cb05.png)

**Comment by damithc** [comment]
> @damithc i'm using the one the oracle version as stated in the link, if i put the javaFxVersion = '11' it doesn't seem to work, having the same error message, but @jamesyeap suggestion of putting it to '14' works

Just a caution that if you don't follow the 'Advisory for Mac user' given in https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html#programming-language you might run into problems later in the iP and the tP even if you can get your own iP to work now using other means.

**Comment by michaelseyo** [comment]
@damithc Hi Prof, i'm not using an m1 mac and using the older intel-based macs, I tried to do the azul build way and downloaded Azul Build OpenJDK 11 appropriate for my system running macOS catalina 10.15.5 here:

![Screenshot 2022-01-31 at 10 18 33 PM](https://user-images.githubusercontent.com/76872115/151809782-253322ae-6d3a-4b3a-bd38-82d5b067623b.png)
 
I've deleted the rest of the SDK versions and only left with the zulu-11.jdk
![Screenshot 2022-01-31 at 10 19 54 PM](https://user-images.githubusercontent.com/76872115/151810004-8a36f8d5-f701-4ae8-80c5-63334c0a8318.png)

I've set the JAVA_HOME to /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home

![Screenshot 2022-01-31 at 10 20 16 PM](https://user-images.githubusercontent.com/76872115/151810063-18e694ec-ce65-47f3-9db8-1188b78d660e.png)

Here's the current project structure:

![Screenshot 2022-01-31 at 10 21 39 PM](https://user-images.githubusercontent.com/76872115/151810301-39980716-dccd-44eb-946b-df38693ab2b7.png)

Still appearing the weird looking font here:
![Screenshot 2022-01-31 at 10 22 14 PM](https://user-images.githubusercontent.com/76872115/151810407-e7f80ce7-50b5-4499-a51b-d2af60c7fb05.png)

"2022-01-31 22:16:36.826 java[96561:7846602] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:]."

**Comment by damithc** [comment]
@michaelseyo Do you face any font issue when running the latest release of AB3?

**Comment by michaelseyo** [comment]
@damithc Yup its a similar issue 
![Screenshot 2022-01-31 at 10 56 59 PM](https://user-images.githubusercontent.com/76872115/151816341-bac9fe3e-5481-4be9-84ad-35479679258b.png)

**Comment by damithc** [comment]
> @damithc Yup its a similar issue
> ![Screenshot 2022-01-31 at 10 56 59 PM](https://user-images.githubusercontent.com/76872115/151816341-bac9fe3e-5481-4be9-84ad-35479679258b.png)

Right, that means the problem is not solved yet.

**Comment by kouyk** [comment]
Hi @michaelseyo I noticed in the screenshot for the azul openjdk, it says jdk and not jdk fx, could you verify that you have downloaded and installed the correct one? It is necessary to install the one that comes with javafx for everything to work. Furthermore, can I confirm that you have been launching the jar files via the command line?

**Comment by michaelseyo** [comment]
@kouyk oh.. it's my mistake i downloaded the one with just JDK instead of JDK FX, thank you so much for your help and also @damithc
