### ISSUE TITLE
How to use JUnit on VS Code?

### ISSUE THREAD

**Issue by ian-from-dover** [nus-cs2103-AY2122S2/forum#59]
I have been using Visual Studio Code for the iP thus far, and I have difficulty trying to find tutorials on how to install JUnit 5 in VS Code. Has anyone had the same problem and found a solution?

I am using macOS 10.15.7 with VS Code 1.63.2 (Universal)

**Comment by takufunkai** [comment]
[I'm not sure if you've seen this](https://code.visualstudio.com/docs/java/java-testing), but it looks quite informative, seems to work with Gradle, which we will be adding to our project this week.

Edit: For the record, I tried to make it work on my project using vscode but gave up after around 10-15 minutes of trying.

**Comment by AllardQuek** [comment]
Am also curious to see if there is a solution to this. From my experience however, working on the iP (and in future the tP) in VS Code is quite a hassle.

My advice would be to try using [Intellij](https://www.jetbrains.com/community/education/#students) instead (you can get an education license for the "Ultimate" version). Intellij might be a better option especially when you are working on the tP with other students in the coming weeks (unless your whole team uses VS Code as well) as you can more easily help each other out when facing issues such as installation of packages, etc. Is there a reason why you are not using VS Code instead of Intellij?

For context, I am a senior who took CS2103 last semester :)

**Comment by cheehongw** [comment]
I also seen that [guide ](https://code.visualstudio.com/docs/java/java-testing) linked by @takufunkai 

The process was pretty automated for me so this may/may not work for you:

1. Get the java extension pack mentioned in the guide (most would have it installed already)
2. Hopefully somehow, this flask icon (Test Explorer) appears in the left panel:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/72195240/151853152-958c0076-589a-42a3-a8ff-e7ea0ae3eb16.png">

3. Click `Enable Java Tests` and select `JUnit Jupiter`
4. It should download a `junit-platform-console-standalone-1.8.2.jar` to the `\lib` folder
5. Check your Test Explorer again and your unit tests should show up there (hopefully) 
6. Might need to check your `Referenced Libraries` under the `Java Projects` tab
<img width="400" src="https://user-images.githubusercontent.com/72195240/151854348-39362b05-ceba-460e-875c-29b095ca3b68.png">

From what I can infer, intelliJ also does a similar thing, except that the junit.jar file is located in a `External Libraries` tab.

**Comment by ianfromdover** [comment]
I finally got JUnit to work on VS Code.

I imported the project into IntelliJ, followed the Gradle and JUnit setup instructions on SE-EDU websites, and then when I could run `./gradlew test` and `./gradlew run` in IntelliJ, the same commands work in the terminal in VS Code.
