### ISSUE TITLE
Unable to Import FXML

### ISSUE THREAD

**Issue by aceszhenwei** [nus-cs2103-AY2122S2/forum#74]
Hi guys. I have reached [part 4](https://se-education.org/guides/tutorials/javaFxPart4.html) of the JavaFX tutorial. However, when I code the `MainWindow.java` file, I am unable to import fxml.FXMLLoader:

`error: package javafx.fxml does not exist`
for:
`import javafx.fxml.FXML;`

My [latest commit](https://github.com/aceszhenwei/ip/commit/63864601bf6411ec7f09a73f281744c0a6e6633d) presents with this issue.

I have copied all the steps from the tutorial, and only updated the 'MainWindow.fxml' to reflect my 'fx:controller':
<img width="646" alt="Screenshot 2022-02-01 at 2 31 18 PM" src="https://user-images.githubusercontent.com/70692871/151922664-97fe1e6a-0893-4362-aee7-4f8781bc95cd.png">

(yes, my package is `duke.duke`)

I have consulted some tips from this [thread](https://github.com/nus-cs2103-AY2122S2/forum/issues/72), but it unfortunately didn't help.

Thanks for helping in advance!

**Comment by AllardQuek** [comment]
Hi @aceszhenwei ! 😄 

1. To be clear, the error message comes from `MainWindow.java` and not `MainWindow.fxml` right? 
2. Why is your package `duke.duke`?
3. Have you tried comparing your code with what your peers who have completed this tutorial have?

**Comment by vimuthm** [comment]
Hi @aceszhenwei , 

I got your iP running by:

 - Removing lines 6 and 58-62 from the `build.gradle` file (version from your linked latest commit): This was because the dependencies property already handles javafx and it seems to me that these additional lines caused some conflicts.
 - Reload gradle
![image](https://user-images.githubusercontent.com/62249192/152098264-f3315cbb-877d-4fde-a06d-323aee51b626.png)

 - The above resolved the javafx import issue but there were other smaller issues that you probably can fix on your own but here's a quick summary:
     - Remove the `handleUserInput()` method in `Duke.java`
     - Revert the `Duke` class to not extend `Application` anymore - This is because we separated the Ui from Duke -> Main, MainWindow
     - I had to make `getResponse()` method in Duke public, as a quick fix, you can see if there's a better way to handle this

On a separate note, you seem to have unchecked exceptions in `Storage.java` that you might want to check :)

Let me know if you face any issues getting the import issue resolved!

edit: As @AllardQuek mentioned, comparing your code to peers' gui commits is a great way to resolve similar issues.

**Comment by aceszhenwei** [comment]
@VimuthM, I managed to get it working! Thanks so much. It totally didn't occur to me that `build.gradle` was causing the issue.
@AllardQuek, the `duke.duke` hails from a long story when I was trying to incorporate gradle, but somehow bugged my entire project. I'll fix it in time.  :pray:

Thanks you guys for the help! I'll definitely be consulting other's commits in the future as well.

**Comment by AllardQuek** [comment]
That's great, all the best @aceszhenwei !
