### ISSUE TITLE
Error when pushing in SourceTree

### ISSUE THREAD

**Issue by janald99** [nus-cs2103-AY2122S2/forum#8]
Hey all,

I am pretty unfamiliar to Git, and am facing troubles trying to push my commit to myfork(origin) on SourceTree as well. 
This is what my current branching looks like, because I used the "reverse commit" function:
![image](https://user-images.githubusercontent.com/77261002/150095146-db358f12-865f-4ba4-9ccd-0876f4338689.png)

Now when I try to push, I have the option to push either 'master', or '(HEAD Detached from 35a4f9d)'. There are errors when pushing either.
When I try to push the HEAD, it says:

The Local branch '(HEAD detached from 35a4f9d)' (Remote branch = '(HEAD detached from 35a4f9d)') is invalid. Ref names must follow git ref-format rules: 
https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html
Completed with errors, see above.

When I try to push master, it says:

Pushing to https://github.com/janald99/ip.git
To https://github.com/janald99/ip.git
 = [up to date]      master -> master
 = [up to date]      Level-1 -> Level-1
 = [up to date]      Level-2 -> Level-2
 ! [rejected]        Level-3 -> Level-3 (already exists)
error: failed to push some refs to 'https://github.com/janald99/ip.git'
 hint: Updates were rejected because the tag already exists in the remote.
Completed with errors, see above.

So firstly, how do I attach the HEAD tag back? Or do I even have to do it - in which case, which branch should I push and of course, how do I fix the error?

Thanks for the help in advance, even though there are so many errors in one request.

**Comment by Spyobird** [comment]
Hi,

I believe that when you reverted a commit you ended up with a local branch with a detached HEAD. Usually HEAD points to the master branch I believe (or whatever is the branch you are working on). The first error is just the name of the local branch has spaces which is not allowed by convention. To return the HEAD back to the master branch, I believe you might just be able to use a git checkout or git switch command to return it. I believe that `git checkout master` may just work. It is also possible that pushing straight to the master branch may return the HEAD back to master.

However, seeing that you reverted your commit, maybe you want to make changes in your new local branch (the detached HEAD). In this case you can always merge your changes to the master branch once you are done. You also would want to rename the branch to something that follows the conventions (https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html).

The second error you have is because you are pushing the 'Level-3' tag to the remote repo (github.com), but the tag already exits on the remote repo. You can either not push the tag (as it is already there) or delete the tag on the remote repo and push it again.

I hope what I said is correct. Anyways hope it helps!

**Comment by janald99** [comment]
Hi, thanks for the help! I am planning to push the head straight to the master branch, however, I am unable to locate the local branch (HEAD) to rename it. Any idea how i can rename this?

**Comment by damithc** [comment]
@janald99 see if [this](https://careerkarma.com/blog/git-detached-head/#:~:text=Re%2DAttaching%20the%20HEAD) helps

**Comment by janald99** [comment]
Thanks prof, I have fixed this issue! The link has provided great help.
