### ISSUE TITLE
JavaFX FXMLLoader issue

### ISSUE THREAD

**Issue by hsiaojietng** [nus-cs2103-AY2122S2/forum#83]
### Directory issue with FXMLLoader
I am trying to load a fxml file using:
```Java
FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("C:\\NUS\\CS2103\\iP\\src\\main\\resources\\duke\\view\\MainWindow.fxml"));
```
But I will always get this error:
![image](https://user-images.githubusercontent.com/56862300/152172901-7546ff31-5a56-420a-8c7b-008b704300ed.png)

This is how my pathing looks like in the project:
![image](https://user-images.githubusercontent.com/56862300/152172644-adc701ea-a648-4867-92a7-953d88ecdb5c.png)

I would love any advice on solving this directory problem, it's kinda frustrating! Thank you in advance!
If more information is needed, this is my GitHub repo: https://github.com/hsiaojietng/ip

**Comment by takufunkai** [comment]
`getResources(String filepath)` will assume you are referring to `main/resources` directory as your base file path. You need to input a filepath relative to the resources directory, for eg: `/duke/view/MainWindow.fxml`. And although you're on Windows, you can do front-slashes instead of back-slashes. Hope this helps.

**Comment by hsiaojietng** [comment]
Nice! This helped alot! Similarly, I had the same problem for my Images. To fix it I just had to change the directory to `/duke/images/whateverPicture.jpg` (Make sure to include the front slash!)
