### ISSUE TITLE
Behavior for "bye" command on Level-10?

### ISSUE THREAD

**Issue by Graphcalibur** [nus-cs2103-AY2122S2/forum#85]
What should the behavior be when the "bye" command is sent for the Level-10 GUI version of our chatbot? Should it close the window? Or should we just ignore it since the user can just close the window on their own?

**Comment by damithc** [comment]
> Should it close the window?

@Graphcalibur that seems a reasonable choice. That way, the user can use either way to close the app.

**Comment by takufunkai** [comment]
Personally, instead of immediately closing the window, I 'shutdown' the chatbot by printing the exit message, disabling the `TextField`, and changing the send button into an exit button, with an `onAction` of closing the stage/window. They can then either click on the exit button, or close the window manually.

This feels more intuitive to me, as printing a valid exit message on `bye` is part of Duke's behaviour.

**Comment by AAlghrairy** [comment]
You could also automatically close the window after a certain time interval

**Comment by damithc** [comment]
The important thing is to think from the user's point of view. If you are the user, which behavior would you prefer?

**Comment by ddx-510** [comment]
For the current stage, I simply make the chatbot send a reply message **The chatbot will say goodbye to you in 3 seconds**
and shut down the app with a delay of 3 seconds after printing out the message.  Because the user would expect the chatbot to say goodbye and "leave" on their own.
