### ISSUE TITLE
Label doesn't wrap text anymore when scrollPane needs to scroll

### ISSUE THREAD

**Issue by jaysmyname** [nus-cs2103-AY2122S2/forum#88]
When the application opens, the label initially wraps the text:

![image](https://user-images.githubusercontent.com/77271680/152308075-3b707b32-24c9-449a-8b6a-98ab8384ccb1.png)

However, after several commands have been added until the scrollPane needs to scroll, the messages all of a sudden just cut themselves, and it gets replaced with ellipsis:

![image](https://user-images.githubusercontent.com/77271680/152308131-e6b6b794-fa95-4ad7-bfd7-9e8a9fe8630c.png)

I've faced this issue in the JavaFX Tutorial too and I still can't figure out how to fix it, I tried setting scrollPane's fitToWidth and fitToHeight true, I tried setting the max height of several things like the labels and the hboxes to the max value, but the same issue still arises.

I've pushed out this new commit with my current changes to the resources: 
https://github.com/jaysmyname/ip/tree/branch-Level-10/src/main/resources/view

I would be greatly appreciative to anyone that can help!

**Comment by Ashuh** [comment]
Set the Min Height of the HBox to `USE_PREF_SIZE`.

**Comment by jaysmyname** [comment]
Thanks so much @Ashuh! Of course I missed the one thing that worked haha

**Comment by yuqitanyq** [comment]
Hey everyone, 

I did the set min-height to USE_PREF_SIZE, here in my dialogbox.java, [link](https://github.com/yuqitanyq/ip/tree/master/src/main/java/duke/ui)

The issue was resolved on mac, (I am a mac user). Screenshot attached below:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/83687861/153738249-0a8f079f-2991-4d41-806a-90d19ac536f6.png">

However, on windows,
the issue still seems to persist after asking my friends to test it out. I was wondering if there is a way for it to make the dialog box work for both windows and mac.

![2022-02-13 12 13 59](https://user-images.githubusercontent.com/83687861/153738325-1400e46f-1eeb-4138-8c00-37b9476ecdd7.jpg)

Appreciate it if anyone could help! Thanks!

**Comment by damithc** [comment]
@yuqitanyq does it work as expected when you use the same JAR file (the one you gave to friends) on your Mac? Perhaps you can share that JAR file here too?

**Comment by damithc** [comment]
@yuqitanyq BTW, this is someone else's thread and it is already closed. Perhaps post a new thread?

**Comment by yuqitanyq** [comment]
@damithc prof yup... it works well on my mac... 

okay let me post it on a new thread!
